spring.datasource.url=jdbc:mysql://localhost:3306/huellitas
spring.datasource.username=huellitas_user
spring.datasource.password=huellitas123...
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver