app.title=Huellitas
mail.empty=El mail no puede estar vacio
mail.not.exists=El mail no se encuentra registrado
mail.multiple.found=No se puede realizar el ingreso con el mail seleccionado
mail.max.length=El mail supera la cantidad de caracteres permitido
mail.already.exists=El mail con el que intenta registrarse ya existe en la base de datos
