package ar.com.huellitas.enums;

public enum Permiso {
	ADMINISTRAR_USUARIOS,
	ADMINISTRAR_MASCOTAS,
	ADMINISTRAR_PERFIL,
	AMINISTRAR_MASCOTAS,
	ADMINISTRAR_PUBLICACIONES,
	CREAR_PUBLICACION,
	CREAR_MASCOTA,
	ADMINISTRAR_PUBLICACIONES_PROPIAS;
}
